
Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/9"

  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 4096
    libvirt.cpus = 2
  end

  config.vm.define "server" do |node|
    node.vm.hostname = "mjulliatS"
    node.vm.network "private_network",
      ip: "192.168.56.110",
      libvirt__network_name: "vagrant-libvirt"

    node.vm.provision "shell", 
      path: "scripts/common.sh",
      name: "Install common"

    node.vm.provision "shell",
      path: "scripts/server.sh",
      name: "Install k3s server",
      args: ["192.168.56.110"]
  end
end

