
Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/9"

  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 1024
    libvirt.cpus = 1
  end

  k3s_token = "secret12345"

  config.vm.define "server" do |node|
    node.vm.hostname = "mjulliatS"
    node.vm.network "private_network",
      ip: "192.168.56.110",
      libvirt__network_name: "vagrant-libvirt"

    node.vm.provision "shell", 
      path: "scripts/common.sh",
      name: "Install common"

    node.vm.provision "shell",
      path: "scripts/server.sh",
      name: "Install k3s server",
      args: ["192.168.56.110", k3s_token]
  end

  config.vm.define "worker" do |node|
    node.vm.hostname = "mjulliatSW"
    node.vm.network "private_network",
      ip: "192.168.56.111",
      libvirt__network_name: "vagrant-libvirt"

    node.vm.provision "shell", 
      path: "scripts/common.sh",
      name: "Install common"
  end
end
